const cloudinary = require("cloudinary").v2;

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true,
});

// Uploads a buffer (from multer memoryStorage) to Cloudinary as a private asset.
// type: "private" keeps the file inaccessible by public URL guessing; downloads
// go through a signed, expiring URL generated by getDownloadUrl below.
function uploadToCloudinary(buffer, folderPath) {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      {
        resource_type: "auto",
        type: "private",
        folder: folderPath,
        use_filename: true,
        unique_filename: true,
      },
      (error, result) => {
        if (error) return reject(error);
        resolve(result);
      }
    );
    stream.end(buffer);
  });
}

// Generates a temporary signed download URL for a private asset.
function getDownloadUrl(publicId, resourceType, format, expiresInSeconds = 300) {
  const expiresAt = Math.floor(Date.now() / 1000) + expiresInSeconds;
  return cloudinary.utils.private_download_url(publicId, format, {
    resource_type: resourceType,
    type: "private",
    expires_at: expiresAt,
  });
}

async function deleteFromCloudinary(publicId, resourceType) {
  await cloudinary.uploader.destroy(publicId, {
    resource_type: resourceType,
    type: "private",
    invalidate: true,
  });
}

module.exports = { uploadToCloudinary, getDownloadUrl, deleteFromCloudinary };
